title: Jarmo Koponen # your name (or website title) here
logo: "images/Jarmo_.png?raw=true" # your photo (or logo) here
description: "+20 years of experience in a global company of high-end computer vision systems, project management, automation, and electrical design.<br> Currently Doctoral Researcher in computer vision.<br><br><a href='https://www.linkedin.com/in/koponenjarmo/'>View My LinkedIn Profile</a>"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Z0DN2QWHY8"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Z0DN2QWHY8');
</script>

  
# Uncomment the following line if you have a Google Analytics tracking ID
# google_analytics: G-Z0DN2QWHY8 # your Google Analytics tracking ID here
