title: Jarmo Koponen # your name (or website title) here
logo: "images/Jarmo_.png?raw=true" # your photo (or logo) here
description: "Doctoral Researcher<br><br>Contact Information:<br><br>Email: <a href='mailto:jarkop@uef.fi'>jarkop@uef.fi</a><br>Phone: +358 40 6311796<br><a href='https://www.linkedin.com/in/koponenjarmo/'>View My LinkedIn Profile</a>"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
# Uncomment the following line if you have a Google Analytics tracking ID
# google_analytics: UA-12345678-9 # your Google Analytics tracking ID here

